/**
       * This file is generated by a script. Do not edit this file.
       * Last update on 2025-04-08T14:46:54.784Z
       */
import type { UUID } from "crypto";

export interface QuizzemDto {
    id: UUID;
    createdAt: Date;
}

export interface CategoryDto extends QuizzemDto {
    category: string;
}

export interface CreateCategoryDto {
    category: string;
}

export interface AnswerFileQuestionDto {
    file: string;
    correctAnswer: string;
}

export interface AnswerMultipleChoicesDto {
    choices: MultipleChoiceDto[];
}

export interface MultipleChoiceDto {
    text: string;
    correctAnswer: boolean;
}

export interface AnswerNumericDto {
    correctAnswer: number;
}

export interface AnswerOrderingDto {
    correctOrder: string[];
}

export interface AnswerTrueFalseDto {
    correctAnswer: boolean;
}

export interface CreateQuestionDto {
    question: string;
    hint: string | null;
    type: EQuestionType;
    timer: number | null;
    answer: Record<string, unknown>;
    categoryId: UUID;
}

export interface QuestionDto extends QuizzemDto {
    question: string;
    hint: string | null;
    type: EQuestionType;
    timer: number | null;
    answer: Record<string, unknown>;
    category: string;
}

export interface PageableQueryDto {
    page: number;
    size: number;
}

export interface PageableDto<T> {
    data: T[];
    page: number;
    totalPages: number;
    size: number;
    totalElements: number;
}

export enum EQuestionType {
    MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
    TRUE_FALSE = "TRUE_FALSE",
    FILL_IN_THE_BLANK = "FILL_IN_THE_BLANK",
    ORDERING = "ORDERING",
    ESTIMATE = "ESTIMATE",
    NUMERIC = "NUMERIC",
    IMAGE_QUESTION = "IMAGE_QUESTION",
    MUSIC_QUESTION = "MUSIC_QUESTION",
    VIDEO_QUESTION = "VIDEO_QUESTION"
}
       